### ISSUE TITLE
ugli

### ISSUE THREAD

**Issue by cktang88** [mwufi/mwufi.github.io#1]

**Comment by mwufi** [comment]
That's a big problem, isn't it

**Comment by mwufi** [comment]
Go to weirdml.com

**Comment by cktang88** [comment]
Looking a bit better, needs some colors and better font - might I suggest Montserrat or Open Sans or https://public-sans.digital.gov/ or https://github.com/rsms/inter

**Comment by mwufi** [comment]
Hah

**Comment by cktang88** [comment]
the real smh is bootstrap/jquery
